import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

const facultyGlyphic = localFont({
  src: '../../public/fonts/Faculty_Glyphic/FacultyGlyphic-Regular.ttf',
  variable: '--font-dota',
  weight: '400',
});

const geistMono = localFont({
  src: '../../public/fonts/Geist_Mono/GeistMono-VariableFont_wght.ttf',
  variable: '--font-mono',
  weight: '100 900',
});

const inter = Inter({
  variable: '--font-ui',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${facultyGlyphic.variable} ${geistMono.variable} ${inter.variable} h-full antialiased`}
    >
      <body className='min-h-full flex flex-col'>{children}</body>
    </html>
  );
}
